name: Daily News Report

on:
  schedule:
    # 한국 시간 09:50은 세계 표준시(UTC)로 00:50 입니다.
    - cron: '50 0 * * *'
  workflow_dispatch: # 수동으로도 실행할 수 있게 해주는 버튼

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml google-generativeai

    - name: Run Python script
      env:
        NCP_CLIENT_ID: ${{ secrets.NCP_CLIENT_ID }}
        NCP_CLIENT_SECRET: ${{ secrets.NCP_CLIENT_SECRET }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: python send_email.py
